In [ ]:
print("Hello World")

Hello World

In [ ]:
#SERIES

In [ ]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([40,50,60])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
pd.Series(arr,index=labels)

a    40
b    50
c    60
dtype: int64

In [ ]:
# DATA FRAMES

In [ ]:
Data = {
     "Name": ["Madhu", "Ram", "Sita", "John"],
    "Age": [21, 22, 20, 23],
    "Marks": [90, 85, 95, 88],
    "City": ["Vijayawada", "Hyderabad", "Chennai", "Delhi"]
}
df = pd.DataFrame(Data)
df

    Name  Age  Marks        City
0  Madhu   21     90  Vijayawada
1    Ram   22     85   Hyderabad
2   Sita   20     95     Chennai
3   John   23     88       Delhi

In [ ]:
List = [
    ["Madhu", 21, 90, "Vijayawada"],
    ["Ram", 22, 85, "Hyderabad"],
    ["Sita", 20, 95, "Chennai"],
    ["John",23,88,"Delhi"]
]
df2 = pd.DataFrame(List)
df2

       0   1   2           3
0  Madhu  21  90  Vijayawada
1    Ram  22  85   Hyderabad
2   Sita  20  95     Chennai
3   John  23  88       Delhi

In [ ]:
List2 = [
    ["Madhu", 21, 90, "Vijayawada"],
    ["Ram", 22, 85, "Hyderabad"],
    ["Sita", 20, 95, "Chennai"],
    ["John",23,88,"Delhi"]
]
idx = ["Name","Age","Marks","City"]
df3 = pd.DataFrame(List2,columns=idx)
df3

    Name  Age  Marks        City
0  Madhu   21     90  Vijayawada
1    Ram   22     85   Hyderabad
2   Sita   20     95     Chennai
3   John   23     88       Delhi

In [ ]:
#SELECTION AND INDEXING OF COLUMNS

In [ ]:
df2

       0   1   2           3
0  Madhu  21  90  Vijayawada
1    Ram  22  85   Hyderabad
2   Sita  20  95     Chennai
3   John  23  88       Delhi

In [ ]:
df

    Name  Age  Marks        City
0  Madhu   21     90  Vijayawada
1    Ram   22     85   Hyderabad
2   Sita   20     95     Chennai
3   John   23     88       Delhi

In [ ]:
df["Name"]

0    Madhu
1      Ram
2     Sita
3     John
Name: Name, dtype: object

In [ ]:
# For selecting multiple columns use double brackets(List)
df[["Name","Age"]]

    Name  Age
0  Madhu   21
1    Ram   22
2   Sita   20
3   John   23

In [ ]:
#Creating a New Column
df["Salary"] = [80000,75000,70000,65000]

In [ ]:
df

    Name  Age  Marks        City  Salary
0  Madhu   21     90  Vijayawada   80000
1    Ram   22     85   Hyderabad   75000
2   Sita   20     95     Chennai   70000
3   John   23     88       Delhi   65000

In [ ]:
df

    Name  Age  Marks        City  Salary
0  Madhu   21     90  Vijayawada   80000
1    Ram   22     85   Hyderabad   75000
2   Sita   20     95     Chennai   70000
3   John   23     88       Delhi   65000

In [ ]:
#REMOVING COLUMNS

In [ ]:
# df.drop("State",axis=1,inplace=True) # axis= 1 means state is there in columns when we add inplace is true then it will deleted from original data
                                     # axis=0  rows when we add inplace is true then it will deleted from original data else it just takes a copy and erase it in that copy

In [ ]:
df

    Name  Age  Marks        City  Salary
0  Madhu   21     90  Vijayawada   80000
1    Ram   22     85   Hyderabad   75000
2   Sita   20     95     Chennai   70000
3   John   23     88       Delhi   65000

In [ ]:
#REMOVING ROWS
df.drop(3,axis=0,inplace=True)

In [ ]:
df

    Name  Age  Marks        City  Salary
0  Madhu   21     90  Vijayawada   80000
1    Ram   22     85   Hyderabad   75000
2   Sita   20     95     Chennai   70000

In [ ]:
#SELECTING ROWS

df.loc[0]

Name           Madhu
Age               21
Marks             90
City      Vijayawada
Salary         80000
Name: 0, dtype: object

In [ ]:
#Selecting Multiple Rows
df.loc[[0,1]]

    Name  Age  Marks        City  Salary
0  Madhu   21     90  Vijayawada   80000
1    Ram   22     85   Hyderabad   75000

In [ ]:
#Another option is iloc (index location)

df.iloc[1]

Name            Ram
Age              22
Marks            85
City      Hyderabad
Salary        75000
Name: 1, dtype: object

In [ ]:
new_data = {
    "Name": ["John", "Anu", "Kiran"],
    "Age": [23, 21, 24],
    "Marks": [88, 92, 81],
    "City": ["Delhi", "Mumbai", "Bangalore"],
    "Salary": [85000, 78000, 72000],
    "Country": ["India", "India", "India"]
}
new_df = pd.DataFrame(new_data)

df = pd.concat([df, new_df], ignore_index=True) #"Ignore_index = Don't keep the old row indexes. Create new indexes starting from 0."

print(df)

    Name  Age  Marks        City  Salary Country
0  Madhu   21     90  Vijayawada   80000     NaN
1    Ram   22     85   Hyderabad   75000     NaN
2   Sita   20     95     Chennai   70000     NaN
3   John   23     88       Delhi   85000   India
4    Anu   21     92      Mumbai   78000   India
5  Kiran   24     81   Bangalore   72000   India

In [ ]:
#SELECTING SUBSETS OF ROWS AND COLUMNS (selecting a paticular portion)

df.loc[[3,4]][["City","Salary",]]

     City  Salary
3   Delhi   85000
4  Mumbai   78000

In [ ]:
#Conditional Selection

#I only want to see those people whose age is above 21

df[df["Age"] > 21]

    Name  Age  Marks       City  Salary Country
1    Ram   22     85  Hyderabad   75000     NaN
3   John   23     88      Delhi   85000   India
5  Kiran   24     81  Bangalore   72000   India

In [ ]:
#I only want to see those people whose age is above 21 and city is hyderabad
df[(df["Age"] > 21) & (df["City"] == "Hyderabad")]
#Note: When we are using double conditions then () brackets should must else it gives error

  Name  Age  Marks       City  Salary Country
1  Ram   22     85  Hyderabad   75000     NaN

In [ ]:
# MISSING DATA

In [ ]:
import numpy as np
import pandas as pd

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

print(df)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
# Checks every value:

# True → value is missing (NaN)
# False → value exists

df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
# Counts total missing values column-wise.

df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
# Checks whether a column contains at least one NaN.
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
# REMOVING MISSING DATA

In [ ]:
df.dropna() #Removes rows that contain at least one NaN
            #Every row has a missing value
            #Empty DataFrame

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.dropna(thresh=1)
df
#thresh means:
#minimum number of NON-NaN values required to keep the row.
#At least 1 non-NaN value must exist.
#All rows satisfy this ✔️

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
# FILLING THE MISSING DATA
# remove -> dropna() row wise
# fill -> fillna() col wise
#search -> isna() col wise

df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.fillna(0,inplace=True)
df

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [ ]:
df

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [ ]:
val = {"A":100,"B":200,"C":300,"D":400}
df.fillna(value=val,inplace=True)
df
# Column A → Fill NaN with 100
# Column B → Fill NaN with 200
# Column C → Fill NaN with 300
# Column D → Fill NaN with 400

       A      B      C      D
0    1.0  200.0    1.0    1.0
1    2.0    2.0    2.0  400.0
2  100.0    3.0    3.0  400.0
3    4.0    4.0  300.0  400.0
4    5.0    5.0  300.0    5.0

In [ ]:
# FIlling the values with mean
df.fillna(df.mean(),inplace=True)
df

       A      B      C      D
0    1.0  200.0    1.0    1.0
1    2.0    2.0    2.0  400.0
2  100.0    3.0    3.0  400.0
3    4.0    4.0  300.0  400.0
4    5.0    5.0  300.0    5.0

In [ ]:
# Merging Joining Concatination
# concatination = Purpose: Stack DataFrames vertically or horizontally.

# Vertical (axis=0) horizontal (axis = 1)

# Merging = Used when DataFrames have a common column.

# join = join() is similar to merge(), but it joins by index by default.

In [ ]:
# When to Use Which?
# Situation	Use
# Append rows	concat()
# Append columns	concat(axis=1)
# Combine using a common column	merge()
# Combine using indexes	join()

In [ ]:
import pandas as pd

# DataFrame 1: Employee information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
pd.merge(employees,salaries,on="employee_id") #(default is inner)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='outer') #Keeps ALL rows from BOTH DataFrames.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='left') #Keeps ALL rows from LEFT DataFrame (employees).
                                                        #If no match exists → NaN.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on="employee_id",how='right') #Keeps ALL rows from RIGHT DataFrame (salaries).

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
pd.concat([df1,df2]) # df1 concat with df2

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df2,df1]) #df2 concat with df1 means df2 will be first then df1

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
pd.concat([df1,df2],axis=1) # concat in rows

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
# Joining Data Frames

In [ ]:
import pandas as pd

# First DataFrame
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [ ]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [ ]:
#Group By Aggrigation

In [ ]:
import pandas as pd

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

print(df)

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
# Group by Category and Calculate the Sum of Sales
cat = df.groupby("Category")['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by store and Calculate the Sum of the Sales
ca = df.groupby("Store")['Sales'].sum()
ca

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
#Group by Multiple Columns
#Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
#Aggrigation

In [ ]:
df['Sales'].mean()
print(df['Sales'].mean())
#Mean,Median,Mode,Min,Max,count,Std

187.5

In [ ]:
h=df['Sales'].agg(['mean','max','min','sum','median','count','std'])
print(h)

mean       187.500000
max        300.000000
min        100.000000
sum       1500.000000
median     190.000000
count        8.000000
std         66.062741
Name: Sales, dtype: float64

In [ ]:
#Pivot Tables
A pivot table is used to summarize and reorganize data. It groups the data and calculates statistics like sum, mean, count, max, min, etc.

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

print(df)

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    415     23   John  January      Q1
1  2023-01-02       B   West    952     41   Mary  January      Q1
2  2023-01-03       C  North    546     71    Bob  January      Q1
3  2023-01-04       D  South    316     68  Alice  January      Q1
4  2023-01-05       A   East    276     30   John  January      Q1
5  2023-01-06       B   West    959     53   Mary  January      Q1
6  2023-01-07       C  North    852     73    Bob  January      Q1
7  2023-01-08       D  South    518     43  Alice  January      Q1
8  2023-01-09       A   East    190     67   John  January      Q1
9  2023-01-10       B   West    480     69   Mary  January      Q1
10 2023-01-11       C  North    945     82    Bob  January      Q1
11 2023-01-12       D  South    115     93  Alice  January      Q1
12 2023-01-13       A   East    546     28   John  January      Q1
13 2023-01-14       B   West    821     74   Mary  January      Q1
14 2023-01-15       C  North    722     72    Bob  January      Q1
15 2023-01-16       D  South    391     14  Alice  January      Q1
16 2023-01-17       A   East    919     13   John  January      Q1
17 2023-01-18       B   West    421     46   Mary  January      Q1
18 2023-01-19       C  North    845     85    Bob  January      Q1
19 2023-01-20       D  South    347     42  Alice  January      Q1

In [ ]:
pivot1 = pd.pivot_table(df,values='Sales',index='Region')
pivot1

        Sales
Region
East    469.2
North   782.0
South   337.4
West    726.6

In [ ]:
pivot2 = pd.pivot_table(df,values='Sales',index='Region',columns='Product')#aggfun = meadian mean
pivot2

Product      A      B      C      D
Region
East     469.2    NaN    NaN    NaN
North      NaN    NaN  782.0    NaN
South      NaN    NaN    NaN  337.4
West       NaN  726.6    NaN    NaN

In [ ]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')#aggfun = meadian mean
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     469.2    NaN    NaN    NaN  32.2   NaN   NaN   NaN
North      NaN    NaN  782.0    NaN   NaN   NaN  76.6   NaN
South      NaN    NaN    NaN  337.4   NaN   NaN   NaN  52.0
West       NaN  726.6    NaN    NaN   NaN  56.6   NaN   NaN

In [ ]:
#Cross Tabs
#crosstab() is used to count the frequency (number of occurrences) between two or more categorical variables.

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [ ]:
# Operations

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

print(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
print(df1.shape)

(5, 3)

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     20 non-null     datetime64[ns]
 1   Product  20 non-null     object
 2   Region   20 non-null     object
 3   Sales    20 non-null     int64
 4   Units    20 non-null     int64
 5   Rep      20 non-null     object
 6   Month    20 non-null     object
 7   Quarter  20 non-null     object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 1.4+ KB
None

In [ ]:
print(df.describe())

                      Date      Sales      Units
count                   20   20.00000  20.000000
mean   2023-01-10 12:00:00  580.40000  54.500000
min    2023-01-01 00:00:00  103.00000  13.000000
25%    2023-01-05 18:00:00  241.50000  37.000000
50%    2023-01-10 12:00:00  653.50000  50.000000
75%    2023-01-15 06:00:00  821.25000  80.500000
max    2023-01-20 00:00:00  958.00000  94.000000
std                    NaN  299.70712  25.934127

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1['B']

0    10
1    20
2    30
3    40
4    50
Name: B, dtype: int64

In [ ]:
def square(a):
  return a**2

df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
# if it need to reflect in the table
df1['B'] = df1['B'].apply(square)

In [ ]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500